version: "3.6"
services:
  arangodb:
    image: arangodb/arangodb:3.7.2
    environment:
      - ARANGO_ROOT_PASSWORD=123456
    ports:
      - "8529:8529"
    volumes:
      - "./data:/var/lib/arangodb3"
