version: '3.1'
services:
  nginx:
    image: nginx
    container_name: nginx
    environment:
      - TZ=Asia/Shanghai
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./conf/default.conf:/etc/nginx/conf.d/default.conf
      - ./logs:/var/log/nginx
      - ./conf/nginx.conf:/etc/nginx/nginx.conf
      #- ./ssl:/ssl_certs

