version: "3.7"
services:
    portainer:
        image: portainer/portainer-ce
        ports:
            - "39900:9000"
        volumes:
            - ./data:/data
            - /var/run/docker.sock:/var/run/docker.sock
        platform: "linux/amd64"
