version: '3.7'
services:
  influxdb:
    image: tutum/influxdb
    environment:
      INFLUXDB_DB: spider
      INFLUXDB_ADMIN_USER: "root" #创建管理员用户
      INFLUXDB_ADMIN_PASSWORD: "123456" #创建管理员密码
      # INFLUXDB_HTTP_AUTH_ENABLED: "true" #启用身份验证。必须设置此设置，或者auth-enabled = true必须在配置文件中设置此设置，以下任何与身份验证相关的选项都可以使用。
      # volumes:
      #   - "./data:/var/lib/influxdb"
      # - "./config/influxdb.conf:/etc/influxdb/influxdb.generated.conf"
    ports:
      - "8083:8083"
      - "8086:8086"
    platform: "linux/amd64"
  grafana:
    image: grafana/grafana
    container_name: influxdb_grafana
    ports:
      - "3001:3000"
